### ISSUE TITLE
讓使用者自行決定在樹狀圖上註釋距離？

### ISSUE THREAD

**Issue by chen1i6c04** [openCDCTW/Benga#20]
是否設置一選項讓使用者決定要不要在樹狀圖上註釋距離
還是一律註釋距離？

**Comment by yi-syong** [comment]
你是否同意 : 設置一選項讓使用者自行決定是否在樹狀圖上標示菌株間的距離 。

比較快的方法是兩種都畫，然後提供給使用者自行選擇。
